### PR TITLE
Udpated build script to clean cached packages

### PR DESCRIPTION
**Pull request by srossross**
@ilanschnell @asmeurer do you see any potential issues from running `conda clean` at the start of the build script?

### CODE REVIEW

**Comment by tswicegood** [comment]
Killing the package cache means you have to re-download all packages.  So long as the index that they're fetching from is on a local network, that's not much of an issue, but it is still traffic.

What are you trying to avoid by not using the package cache?

**Comment by srossross** [comment]
The machines fill up with fast with 1) All of the old build tarballs 2) the unused dependencies from previous builds.

It was also my understanding that this only removes packages with 0 links.

That is why I tagged @ilanschnell @asmeurer for feedback because I was not sure about exactly what  this doing.

**Comment by ilanschnell** [comment]
Yes, that is correct, only packages which are not linked into any environment are removed.  However, the build environment is removed after each build, so the build dependencies would not be cached.
I think a better solution would be to clean the cache using a cronjob, which clears the cache every week or so.

**Comment by tswicegood** [comment]
I would think the build tarballs represent a larger amount of files.  Does it make sense to start with that, then see how the pkg cache goes?  If there's any reporting / monitoring of the build box, it would be interesting to see what a week's worth of dependencies looks like.

I think @ilanschnell is on the right track though.  Clearing once a week or once a day would be more efficient.  This might be an interesting use for `conda` with some sort of new option like `conda clean -p --age "1 week"` which would look for packages that haven't been used for more than a week and kill those.

**Comment by srossross** [comment]
> This might be an interesting use for conda with some sort of new option like conda clean -p --age "1 week" which would look for packages that haven't been used for more than a week and kill those.

@tswicegood I like that idea

**Comment by tswicegood** [comment]
Thanks, I stole it [from git][1]. :-)  Look for `--since` or `--until`.  They have a bunch of functions that take dates as options and allow you to slice off chunks of data based on dates.

[1]: http://git-scm.com/docs/git-log

**Comment by srossross** [comment]
Merging this - I will revisit the cron idea later

**Pull request merged**
